name: Build Docker Container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-images:
    name: Build static Native DB image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_WRITE_TOKEN }}

      - name: Login to Digital Ocean
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
          password: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository }}'

      - name: Build Image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}:latest
            registry.digitalocean.com/${{ env.OWNER_LC }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          build-args: |
            ${{ env.BUILD_ARGS }}
